# Generated by Django 5.1 on 2024-09-28 18:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=60)),
                ('nbre_de_place', models.CharField(max_length=60)),
                ('rdv', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=0)),
                ('description', models.TextField(max_length=400)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=400)),
                ('joindate', models.CharField(max_length=60)),
                ('main_menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.mainmenu')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('slug', models.CharField(max_length=60, unique=True)),
                ('status', models.BooleanField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='pictures')),
                ('description', models.TextField(max_length=400)),
                ('price', models.CharField(default='3', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.mainmenu')),
            ],
        ),
    ]
