# Generated by Django 5.1 on 2024-08-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='fullname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=60),
        ),
    ]
